# Generated by Django 3.2.25 on 2024-05-16 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('name', models.CharField(choices=[('Arkéa - B & B Hotels', 'Arkéa - B & B Hotels'), ('Astana Qazaqstan Team', 'Astana Qazaqstan Team'), ('Alpecin - Deceuninck', 'Alpecin - Deceuninck'), ('BORA - hansgrohe', 'BORA - hansgrohe'), ('Bahrain - Victorious', 'Bahrain - Victorious'), ('Cofidis', 'Cofidis'), ('Team dsm - firmenich', 'Team dsm - firmenich'), ('Groupama - FDJ', 'Groupama - FDJ'), ('INEOS Grenadiers', 'INEOS Grenadiers'), ('Intermarché - Wanty', 'Intermarché - Wanty'), ('Team Jayco AlUla', 'Team Jayco AlUla'), ('Lidl - Trek', 'Lidl - Trek'), ('Movistar Team', 'Movistar Team'), ('PostNL', 'PostNL'), ('Soudal Quick - Step', 'Soudal Quick - Step'), ('UAE Team Emirates', 'UAE Team Emirates'), ('Team Visma | Lease a Bike', 'Team Visma | Lease a Bike')], max_length=50)),
                ('category', models.CharField(choices=[('1.1', '1.1'), ('World Tour', 'World Tour'), ('2.1', '2.1'), ('2.2', '2.2')], max_length=20)),
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, serialize=False, to='team_manager.teammanager')),
                ('logo', models.URLField(max_length=300)),
            ],
        ),
    ]
