# Generated by Django 3.2.25 on 2024-05-16 10:34

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cyclist',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('about', models.TextField(max_length=1000)),
                ('strava', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
