# Generated by Django 3.2.25 on 2024-05-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyclist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cyclist',
            name='specialty',
            field=models.CharField(choices=[('One Day Races', 'One Day Races'), ('General Classification', 'General Classification'), ('Time Trail', 'Time Trail'), ('Sprint', 'Sprint'), ('Climber', 'Climber'), ('Hills', 'Hills')], default='TT', max_length=50),
            preserve_default=False,
        ),
    ]
